<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DataDrivenTestSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>79a65625-ab4a-406a-9211-816caf2b83bf</testSuiteGuid>
   <testCaseLink>
      <guid>03f61d9f-b6f8-4492-a0e1-34fe301efac7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DataDrivenTC</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>a72915e2-c8b4-476d-a9ef-6096c0c4cd14</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TestData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>a72915e2-c8b4-476d-a9ef-6096c0c4cd14</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>countryCode</value>
         <variableId>3f96de56-d506-4d2a-b688-9e8ca5d9a496</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>a72915e2-c8b4-476d-a9ef-6096c0c4cd14</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Capital</value>
         <variableId>278083d2-ad85-4889-87b4-bcfec7506513</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>a72915e2-c8b4-476d-a9ef-6096c0c4cd14</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Currency1</value>
         <variableId>9999dcbb-f7ef-4153-9eeb-abdfd3c83ee5</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
